export enum DeliveryStatus {
    SEARCHING='SEARCHING',
    ASSIGNED='ASSIGNED',
    ARRIVED_MERCHANT='ARRIVED_MERCHANT',
    PICKED_UP='PICKED_UP',
    DELIVERING='DELIVERING',
    DELIVERED='DELIVERED',
    FAILED='FAILED',
    CANCELLED='CANCELLED',
}